// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvcv0sbGxI6mYGfeILKZoukxrPMcpc1Y8',
    appId: '1:570636343294:web:b10ef7b018d5b2962312af',
    messagingSenderId: '570636343294',
    projectId: 'final-project-flutter-45925',
    authDomain: 'final-project-flutter-45925.firebaseapp.com',
    storageBucket: 'final-project-flutter-45925.firebasestorage.app',
    measurementId: 'G-H5RH8CL5T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9derU1yO9OFX8XAbMfrmYce7FG4gK_tY',
    appId: '1:570636343294:android:65b715a958c3e2122312af',
    messagingSenderId: '570636343294',
    projectId: 'final-project-flutter-45925',
    storageBucket: 'final-project-flutter-45925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSrYJCw2-V3lW7_LPrl8c24cR0gn1vgc',
    appId: '1:570636343294:ios:ca4020d7d4b2fbdc2312af',
    messagingSenderId: '570636343294',
    projectId: 'final-project-flutter-45925',
    storageBucket: 'final-project-flutter-45925.firebasestorage.app',
    iosBundleId: 'com.example.finalprojectflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSrYJCw2-V3lW7_LPrl8c24cR0gn1vgc',
    appId: '1:570636343294:ios:ca4020d7d4b2fbdc2312af',
    messagingSenderId: '570636343294',
    projectId: 'final-project-flutter-45925',
    storageBucket: 'final-project-flutter-45925.firebasestorage.app',
    iosBundleId: 'com.example.finalprojectflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvcv0sbGxI6mYGfeILKZoukxrPMcpc1Y8',
    appId: '1:570636343294:web:f631628eb3aea75a2312af',
    messagingSenderId: '570636343294',
    projectId: 'final-project-flutter-45925',
    authDomain: 'final-project-flutter-45925.firebaseapp.com',
    storageBucket: 'final-project-flutter-45925.firebasestorage.app',
    measurementId: 'G-ZGP78KYWET',
  );
}
